### PR TITLE
C++11 lambda expressions support

### PR DESCRIPTION
**Pull request by afernandez90**
C code generator to generate C++11 lambda expressions for DSL-level lambda expressions

### CODE REVIEW

**Comment by TiarkRompf** [comment]
Thanks for the PR! Can you investigate the failing tests?

**Comment by afernandez90** [comment]
Oops! Yes! I forgot to update the test on the repo. There you go :).

Thanks to you for the great work!

**Comment by afernandez90** [comment]
Merge-in please? :)

**Comment by TiarkRompf** [comment]
merged :) thanks again!

**Pull request merged**
